### ISSUE TITLE
Need to enable RDP on Win10

### ISSUE THREAD

**Issue by jdhitsolutions** [theJasonHelmick/PS-AutoLab-Env#57] opened 2016-11-10 19:49 UTC
In order to use VMConnect and enhanced session with full screen on the Windows 10 clients, remote desktop access must be enabled. I seem to recall this is a simple registry setting. I'm looking through my notes.

**Comment by jdhitsolutions** [comment] 2016-11-10 20:00
```
Set-ItemProperty -Path "HKLM:\System\ControlSet001\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
```
A value of 1 would disable remote desktop. This should be easy enough to set the Registry resource.

**Comment by theJasonHelmick** [comment] 2016-11-10 20:39
Added in latest merge!!!!!

**Comment by theJasonHelmick** [comment] 2016-11-11 00:02
@jdhitsolutions I added as a custom bootstrap -- not as a resource -- the graphical checkbox is selected, but it doesn't work.  If you manually turn it off in the graphical and back on --- then it works....I think there is another setting that must be missing

**Comment by theJasonHelmick** [comment] 2016-11-11 00:31
I actually 'think' I know what the problem is --- the graphic enables the firewall ports.......I'm controlling the firewall -- so I just need to figure out those settings....probably can't tonight as trying to get DC to converge with ADCS....but will get to this

**Comment by theJasonHelmick** [comment] 2016-11-11 01:30
@jdhitsolutions @majst32 Solved... not in master yet...but will be tomorrow and for release...used registry resource and opened correct firewall settings.

**Comment by theJasonHelmick** [comment] 2016-11-11 01:30
Closing

**Closed by theJasonHelmick** 2016-11-11 01:30 UTC
